export enum Chain {
  ZORA = 'ZORA',
  SOLANA = 'SOLANA'
}

export interface Coin {
  id: string;
  name: string;
  ticker: string;
  chain: Chain;
  price: number;
  imageUrl: string;
  creator: string;
}

export interface Pack {
  id: string;
  name: string;
  description: string;
  coins: Coin[];
  createdAt: string;
  owner: string;
  lore?: string; // Generated by AI
  priceHistory: number[]; // For the chart
  currentPrice: number;
}

export enum AppState {
  LOCKED = 'LOCKED',
  CURATING = 'CURATING',
  MINTING = 'MINTING',
  MINTED = 'MINTED'
}
